# auto-release.yml - Semantic Versioning & Auto-Release
# Automated releases with changelog generation and asset uploads
# Part of GitHub Actions Premium Pack

name: Auto Release

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - auto
          - patch
          - minor
          - major
      prerelease:
        description: 'Pre-release identifier (e.g., beta, rc)'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  analyze:
    name: Analyze Commits
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.analysis.outputs.should_release }}
      version_type: ${{ steps.analysis.outputs.version_type }}
      changelog: ${{ steps.analysis.outputs.changelog }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: latest_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Latest tag: $TAG"

      - name: Analyze commits
        id: analysis
        run: |
          LATEST_TAG="${{ steps.latest_tag.outputs.tag }}"

          # Get commits since last tag
          COMMITS=$(git log $LATEST_TAG..HEAD --pretty=format:"%s" 2>/dev/null || git log --pretty=format:"%s")

          # Determine version type from commit messages (Conventional Commits)
          if echo "$COMMITS" | grep -qE "^(BREAKING CHANGE|!:)"; then
            VERSION_TYPE="major"
          elif echo "$COMMITS" | grep -qE "^feat(\(.+\))?:"; then
            VERSION_TYPE="minor"
          elif echo "$COMMITS" | grep -qE "^(fix|perf|refactor)(\(.+\))?:"; then
            VERSION_TYPE="patch"
          else
            VERSION_TYPE="none"
          fi

          # Override with manual input if provided
          if [[ "${{ github.event.inputs.version_type }}" != "" && "${{ github.event.inputs.version_type }}" != "auto" ]]; then
            VERSION_TYPE="${{ github.event.inputs.version_type }}"
          fi

          # Check if we should release
          if [[ "$VERSION_TYPE" == "none" && "${{ github.event_name }}" != "workflow_dispatch" ]]; then
            echo "should_release=false" >> $GITHUB_OUTPUT
            echo "No releasable changes found"
            exit 0
          fi

          echo "should_release=true" >> $GITHUB_OUTPUT
          echo "version_type=$VERSION_TYPE" >> $GITHUB_OUTPUT

          # Generate changelog
          echo "Generating changelog..."
          CHANGELOG=""

          # Breaking changes
          BREAKING=$(git log $LATEST_TAG..HEAD --pretty=format:"- %s (%h)" --grep="^BREAKING CHANGE" --grep="^!:" 2>/dev/null || true)
          if [[ -n "$BREAKING" ]]; then
            CHANGELOG+="### Breaking Changes\n$BREAKING\n\n"
          fi

          # Features
          FEATURES=$(git log $LATEST_TAG..HEAD --pretty=format:"- %s (%h)" --grep="^feat" 2>/dev/null || true)
          if [[ -n "$FEATURES" ]]; then
            CHANGELOG+="### Features\n$FEATURES\n\n"
          fi

          # Fixes
          FIXES=$(git log $LATEST_TAG..HEAD --pretty=format:"- %s (%h)" --grep="^fix" 2>/dev/null || true)
          if [[ -n "$FIXES" ]]; then
            CHANGELOG+="### Bug Fixes\n$FIXES\n\n"
          fi

          # Performance
          PERF=$(git log $LATEST_TAG..HEAD --pretty=format:"- %s (%h)" --grep="^perf" 2>/dev/null || true)
          if [[ -n "$PERF" ]]; then
            CHANGELOG+="### Performance\n$PERF\n\n"
          fi

          # Other commits
          OTHER=$(git log $LATEST_TAG..HEAD --pretty=format:"- %s (%h)" --invert-grep --grep="^feat" --grep="^fix" --grep="^perf" --grep="^BREAKING" --grep="^!:" 2>/dev/null || true)
          if [[ -n "$OTHER" ]]; then
            CHANGELOG+="### Other Changes\n$OTHER\n\n"
          fi

          # Write changelog to file for later use
          echo -e "$CHANGELOG" > changelog.md

          echo "Version type: $VERSION_TYPE"

      - name: Upload changelog
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: changelog.md

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: analyze
    if: needs.analyze.outputs.should_release == 'true'
    outputs:
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download changelog
        uses: actions/download-artifact@v4
        with:
          name: changelog

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Calculate version
        id: version
        run: |
          # Get current version from package.json or last tag
          if [[ -f "package.json" ]]; then
            CURRENT=$(node -p "require('./package.json').version" 2>/dev/null || echo "0.0.0")
          else
            CURRENT=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//' || echo "0.0.0")
          fi

          # Parse version parts
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"

          # Bump version
          case "${{ needs.analyze.outputs.version_type }}" in
            major)
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            minor)
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            patch)
              PATCH=$((PATCH + 1))
              ;;
          esac

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          # Add prerelease suffix if specified
          if [[ -n "${{ github.event.inputs.prerelease }}" ]]; then
            NEW_VERSION="$NEW_VERSION-${{ github.event.inputs.prerelease }}"
          fi

          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version: $NEW_VERSION"

      - name: Update package.json
        if: hashFiles('package.json') != ''
        run: |
          npm version ${{ steps.version.outputs.version }} --no-git-tag-version

      - name: Commit version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add -A
          git diff --staged --quiet || git commit -m "chore: bump version to ${{ steps.version.outputs.version }}"
          git push

      - name: Create tag
        run: |
          git tag ${{ steps.version.outputs.tag }}
          git push origin ${{ steps.version.outputs.tag }}

      - name: Build release assets
        run: |
          # Build if script exists
          if npm run build --if-present; then
            echo "Build completed"
          fi

          # Create archive
          mkdir -p release-assets

          if [[ -d "dist" ]]; then
            tar -czvf release-assets/dist.tar.gz dist/
            zip -r release-assets/dist.zip dist/
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.version }}
          body_path: changelog.md
          files: release-assets/*
          prerelease: ${{ github.event.inputs.prerelease != '' }}
          generate_release_notes: false

  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: release
    if: hashFiles('package.json') != ''
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.release.outputs.tag }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Publish to npm
        if: vars.NPM_PUBLISH == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [release, publish]
    if: always() && needs.release.result == 'success'
    steps:
      - name: Download changelog
        uses: actions/download-artifact@v4
        with:
          name: changelog

      - name: Slack notification
        if: vars.SLACK_WEBHOOK_URL
        run: |
          CHANGELOG=$(cat changelog.md | head -50)
          curl -X POST "${{ vars.SLACK_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"text\": \"New Release: ${{ needs.release.outputs.tag }}\",
              \"blocks\": [
                {
                  \"type\": \"section\",
                  \"text\": {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*New Release Published* :rocket:\\n\\n*Version:* \`${{ needs.release.outputs.version }}\`\\n*Tag:* \`${{ needs.release.outputs.tag }}\`\\n\\n<https://github.com/${{ github.repository }}/releases/tag/${{ needs.release.outputs.tag }}|View Release>\"
                  }
                }
              ]
            }"
