#!/bin/bash
# AWS Setup Helper Script
# =======================
# Creates SSH key pair and prepares Terraform variables.

set -e

KEY_NAME="autonomous-claude"
REGION="${AWS_REGION:-us-east-1}"

echo "=========================================="
echo "Autonomous Claude - AWS Setup"
echo "=========================================="
echo ""

# Check AWS CLI is configured
if ! aws sts get-caller-identity &>/dev/null; then
    echo "ERROR: AWS CLI not configured. Run 'aws configure' first."
    exit 1
fi

echo "AWS Account: $(aws sts get-caller-identity --query Account --output text)"
echo "Region: $REGION"
echo ""

# Check if key pair already exists
if aws ec2 describe-key-pairs --key-names "$KEY_NAME" --region "$REGION" &>/dev/null; then
    echo "Key pair '$KEY_NAME' already exists in AWS."
    if [ -f ~/.ssh/${KEY_NAME}.pem ]; then
        echo "Local key file found: ~/.ssh/${KEY_NAME}.pem"
    else
        echo "WARNING: Local key file NOT found. You may need to recreate the key pair."
        echo "To recreate, delete the existing key pair first:"
        echo "  aws ec2 delete-key-pair --key-name $KEY_NAME --region $REGION"
        exit 1
    fi
else
    echo "Creating SSH key pair: $KEY_NAME"
    
    # Create key pair and save private key
    aws ec2 create-key-pair \
        --key-name "$KEY_NAME" \
        --key-type ed25519 \
        --region "$REGION" \
        --query 'KeyMaterial' \
        --output text > ~/.ssh/${KEY_NAME}.pem
    
    chmod 600 ~/.ssh/${KEY_NAME}.pem
    echo "Private key saved to: ~/.ssh/${KEY_NAME}.pem"
fi

# Get current public IP for security group
echo ""
echo "Getting your public IP for security group..."
MY_IP=$(curl -s https://checkip.amazonaws.com)
echo "Your IP: $MY_IP"

# Create terraform.tfvars
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$(dirname "$SCRIPT_DIR")/terraform"

cat > "$TERRAFORM_DIR/terraform.tfvars" << EOF
# Auto-generated by aws_setup.sh
key_name         = "$KEY_NAME"
aws_region       = "$REGION"
allowed_ssh_cidr = "${MY_IP}/32"
instance_type    = "t3.medium"
volume_size      = 50
project_name     = "autonomous-claude"
environment      = "dev"
EOF

echo ""
echo "Created terraform.tfvars with your settings."
echo ""
echo "=========================================="
echo "Setup Complete! Next steps:"
echo "=========================================="
echo ""
echo "1. Deploy infrastructure:"
echo "   cd $(dirname "$SCRIPT_DIR")/terraform"
echo "   terraform init"
echo "   terraform apply"
echo ""
echo "2. After deploy, SSH with:"
echo "   ssh -i ~/.ssh/${KEY_NAME}.pem ubuntu@<EC2_IP>"
echo ""

